In [1]:
import numpy

In [2]:
n = numpy.arange(27) #Creating one dimentional array 

In [3]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [4]:
n.reshape(3,9) #reshaping the one dimentinal array to 2 dimentional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3) #reshaping the one dimentional array to 3 dimentional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
#We can convert the simple array list to numpy array list
nm = numpy.asarray([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
nm

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [9]:
type(nm)

numpy.ndarray

In [10]:
import cv2

In [21]:
im_g_bgr = cv2.imread("smallgray.png", 1) # 1 means we are reading the image in RBG(red, blue, green) scale
im_g_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [22]:
#in RGB case it's bit confusing becuase we have 3 rows in image and it's showing 5. it is just showing the rows as columns
#and columns as rows. 
#one more thing to remember here is first block of values is with respect to BLUE. 2 is of GREEN and 3rd is of RED
#so order is BGR
im_g = cv2.imread("smallgray.png", 0) #0 here means we are reading the image in gray scale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [23]:
# our image is in grayscale so it's easy to read the image in grayscale and we can see we have 3 rows and 5 columns 
# of pixels in image
#same is the case with array value
#first value 187 is indicating the grayscal of our first pixel which is at first row first column
#and all the other values respectivity

In [24]:
# Now we will see how to create an image with openCv. it's very simple

In [25]:
cv2.imwrite("new_small_img.png", im_g) # format is cv2.imwrite("name-of-the-new-image.png", numpy array for image)

True

In [26]:
# True means new image is been created

In [27]:
cv2.imwrite("new_img_from_bgr.png", im_g_bgr)

True

In [28]:
# Successfully created the image from BGR numpy array