In [1]:
import numpy

In [2]:
n = numpy.arange(27) #Creating one dimentional array 

In [3]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [4]:
n.reshape(3,9) #reshaping the one dimentinal array to 2 dimentional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3) #reshaping the one dimentional array to 3 dimentional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
#We can convert the simple array list to numpy array list
nm = numpy.asarray([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
nm

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [12]:
type(nm)
import cv2

ImportError: DLL load failed: The specified module could not be found.

In [11]:
import sys

In [13]:
sys.path.append('/Users/Haseeb Bhai/Anaconda3/Lib/site-packages')

In [19]:
import cv2

ImportError: DLL load failed: The specified module could not be found.