In [1]:
import numpy

In [2]:
n = numpy.arange(27) #Creating one dimentional array 

In [3]:
print(n)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26]


In [4]:
n.reshape(3,9) #reshaping the one dimentinal array to 2 dimentional array

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n.reshape(3,3,3) #reshaping the one dimentional array to 3 dimentional array

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [6]:
#We can convert the simple array list to numpy array list
nm = numpy.asarray([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [7]:
nm

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [8]:
type(nm)

numpy.ndarray

In [9]:
import cv2

In [10]:
im_g_bgr = cv2.imread("smallgray.png", 1) # 1 means we are reading the image in RBG(red, blue, green) scale
im_g_bgr

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [11]:
#in RGB case it's bit confusing becuase we have 3 rows in image and it's showing 5. it is just showing the rows as columns
#and columns as rows. 
#one more thing to remember here is first block of values is with respect to BLUE. 2 is of GREEN and 3rd is of RED
#so order is BGR
im_g = cv2.imread("smallgray.png", 0) #0 here means we are reading the image in gray scale
im_g

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [12]:
# our image is in grayscale so it's easy to read the image in grayscale and we can see we have 3 rows and 5 columns 
# of pixels in image
#same is the case with array value
#first value 187 is indicating the grayscal of our first pixel which is at first row first column
#and all the other values respectivity

In [13]:
# Now we will see how to create an image with openCv. it's very simple

In [14]:
cv2.imwrite("new_small_img.png", im_g) # format is cv2.imwrite("name-of-the-new-image.png", numpy array for image)

True

In [15]:
# True means new image is been created

In [16]:
cv2.imwrite("new_img_from_bgr.png", im_g_bgr)

True

In [17]:
# Successfully created the image from BGR numpy array

In [19]:
# Now slicing of numpy array 
im_g[0:2] #row slicing: this code means we want row from 0 to 2(excluded)

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147]], dtype=uint8)

In [20]:
im_g[0:2,2:4] # 0:2(define rows range), 2:4(define the columns range)

array([[104, 121],
       [255, 255]], dtype=uint8)

In [21]:
# Now we can create an image with the help of cv2.imwrite()
#which means we can slice an image with numpy array slicing

In [22]:
# we can get specific columns too
im_g[:,2:4]

array([[104, 121],
       [255, 255],
       [255,  97]], dtype=uint8)

In [24]:
#we can also get one entry
im_g[2,4] # value at 3rd row and 5th columns of im_g numpy array

182

In [25]:
#Now iteration through numpy array

In [26]:
for i in im_g: #iterate thorough rows of array
    print(i)

[187 158 104 121 143]
[198 125 255 255 147]
[209 134 255  97 182]


In [27]:
for i in im_g.T: #iterate through columns of numpy array
    print(i)

[187 198 209]
[158 125 134]
[104 255 255]
[121 255  97]
[143 147 182]


In [30]:
for i in im_g.flat: #iterate through each value
    print(i, end= " ")

187 158 104 121 143 198 125 255 255 147 209 134 255 97 182 

In [31]:
# Now stacking the numpy array
ims = numpy.hstack((im_g, im_g, im_g, im_g, im_g)) # .hstack only accepts one arg so we send a tuple of multiple array of same
#dimentions
# .h means horizental stack

In [32]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143 187 158 104
  121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147 198 125 255
  255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182 209 134 255
   97 182 209 134 255  97 182]]


In [33]:
ims = numpy.vstack((ims, ims, ims, ims, ims)) # .vstack is for vertical stack and only accepts one arg. so we send tuple of same dimen

In [34]:
print(ims)

[[187 158 104 121 143 187 158 104 121 143 187 158 104 121 143 187 158 104
  121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147 198 125 255
  255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182 209 134 255
   97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143 187 158 104 121 143 187 158 104
  121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147 198 125 255
  255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182 209 134 255
   97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143 187 158 104 121 143 187 158 104
  121 143 187 158 104 121 143]
 [198 125 255 255 147 198 125 255 255 147 198 125 255 255 147 198 125 255
  255 147 198 125 255 255 147]
 [209 134 255  97 182 209 134 255  97 182 209 134 255  97 182 209 134 255
   97 182 209 134 255  97 182]
 [187 158 104 121 143 187 158 104 121 143 187 158 104 1

In [35]:
# Now let's create an image of this array
cv2.imwrite("stacked_images.png", ims)

True

In [36]:
#Now check the folder and see the newly created image

In [38]:
# We can also split the array
lst = numpy.vsplit(ims, 5) # .vsplit() takes 2 args first is numpy array and second one spliter
lst

[array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143, 187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147, 198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182, 209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143, 187, 158, 104, 121, 143, 187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147, 198, 125, 255, 255, 147, 198, 125, 255,
         255, 147, 198, 125, 255, 255, 147, 198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182, 209, 134, 255,  97, 182, 209, 134, 255,
          97, 182, 209, 134, 255,  97, 182, 209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143, 187, 158, 104, 121, 143, 187, 158, 104,
         121, 143, 187, 158, 104

In [39]:
# let's see what we got here by creating an image of one item of above list
type(lst)

list

In [40]:
cv2.imwrite("vertical_split_result_img.png", lst[1])

True

In [41]:
# See the image in the folder 

In [42]:
h_lst = numpy.hsplit(lst[1], 5) #.hsplit is horizental split. seding first item of above list and split factor 5

In [43]:
h_lst

[array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8),
 array([[187, 158, 104, 121, 143],
        [198, 125, 255, 255, 147],
        [209, 134, 255,  97, 182]], dtype=uint8)]

In [45]:
#Let's take one item of above list and create an image from it
cv2.imwrite("h_and_v_split.png", h_lst[0])

True

In [46]:
# Now check your folder to see the newly created image by the name of h_and_v_split.png
# Yeah! We get the original image back